---
- name: Create Azure VM with Public IP
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - azure.azcollection

  tasks:

    # 1. Resource Group
    - name: Create resource group
      azure_rm_resourcegroup:
        name: Groupe5ResourceGroup
        location: westeurope

    # 2. Virtual Network
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: Groupe5ResourceGroup
        name: Groupe5VNet
        address_prefixes: "10.0.0.0/16"

    # 3. Subnet
    - name: Create subnet
      azure_rm_subnet:
        resource_group: Groupe5ResourceGroup
        name: Groupe5Subnet
        address_prefix: "10.0.1.0/24"
        virtual_network: Groupe5VNet

    # 4. Public IP
    - name: Create public IP
      azure_rm_publicipaddress:
        resource_group: Groupe5ResourceGroup
        allocation_method: Static
        sku: Standard
        name: Groupe5PublicIP

    # 5. Network Interface
    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: Groupe5ResourceGroup
        name: Groupe5NIC
        location: westeurope
        virtual_network: Groupe5VNet
        subnet_name: Groupe5Subnet
        ip_configurations:
          - name: ipconfig1
            public_ip_address_name: Groupe5PublicIP

    # 6. Virtual Machine
    - name: Create virtual machine
      azure_rm_virtualmachine:
        resource_group: Groupe5ResourceGroup
        name: Groupe5VM
        vm_size: Standard_B2ats_v2
        admin_username: azuremerlus
        admin_password: "Groupe5Merlu$"
        network_interfaces: Groupe5NIC
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: "24.04-LTS"
          version: latest
